---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{ source_url }}?rev={{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: jhutar-1-app-vwkms
    appstudio.openshift.io/component: jhutar-1-app-vwkms-comp-0
    pipelines.appstudio.openshift.io/type: build
  name: jhutar-1-app-vwkms-comp-0-on-push
  namespace: jhutar-1-tenant
spec:
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: ociStorage
      value: "quay.io/redhat-user-workloads/$(context.taskRun.namespace)/jhutar-1-app-vwkms-comp-0:$(params.revision)"
    - name: build-architectures
      value:
        - aarch64
        - x86_64
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://gitlab.com/fedora/infrastructure/konflux/rpmbuild-pipeline.git
      - name: revision
        value: "main"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-jhutar-1-app-vwkms-comp-0
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
